coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%

    patch:
      default:
        target: 80%
        threshold: 1%

github_checks:
  annotations: true

comment:
  layout: "newheader, diff, flags, files"


profiling:
  critical_files_paths:
    - src/app/*
    - src/components/*

component_management:
  individual_components:
    - component_id: app
      name: App
      paths:
        - src/app/**
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 80%

    - component_id: components
      name: Components
      paths:
        - src/components/**
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 80%


ignore:
  - "node_modules/**"
  - ".next/**"
  - "coverage/**"
  - "public/**"
  - "**/*.config.js"
  - "**/*.config.cjs"
  - "**/*.config.mjs"
  - "**/*.config.ts"
  - "next-env.d.ts"
  - "**/*.d.ts"
  - "**/__tests__/**"
  - "**/*.test.*"
  - "**/*.spec.*"
  - "jest.setup.*"
  - "playwright-report/**"
  - "test-results/**"
  - "e2e/**"
  - "tests/e2e/**"
