name: CI
run-name: CI Pipeline - PR#${{ github.event.pull_request.number }} by @${{ github.actor }}
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: ./.github/workflows/dependency-review.yaml
    permissions:
      contents: read
      pull-requests: write

  run-tests:
    needs: dependency-review
    uses: ./.github/workflows/test-build.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    permissions:
      pull-requests: write
  scan-gitguardian:
    needs:
      - run-tests
    uses: ./.github/workflows/gitguardian.yaml
    permissions:
      contents: read
    secrets:
      GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  secret-scan-gitleaks:
    needs:
      - run-tests
    uses: ./.github/workflows/gitleaks.yaml
    permissions:
      contents: read
