name: Deploy to Vercel

run-name: "Deploy to ${{ inputs.github-env }} | ${{ github.actor }} | Vercel"
on:
  workflow_dispatch:
    inputs:
      github-env:
        description: "GitHub Deployment Environment"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{inputs.github-env}}
  cancel-in-progress: true
jobs:
  run-tests:
    uses: ./.github/workflows/test-build.yaml
    permissions:
      pull-requests: write
      contents: read
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  deploy:
    needs:
      - run-tests
    runs-on: ubuntu-24.04
    outputs:
      vercel-url: "${{ steps.deploy-vercel.outputs.preview-url }}"
    environment:
      name: ${{ inputs.github-env }}
      url: "${{ steps.deploy-vercel.outputs.preview-url }}"
    permissions:
      deployments: write
    steps:
      - name: Checkout Reposiotry Code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node Environment
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ inputs.github-env == 'production' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts (Production)
        if: inputs.github-env == 'production'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
          NEXT_PUBLIC_SENTRY_DISABLED: false
          SENTRY_ORGANIZATION: ${{ secrets.SENTRY_ORGANIZATION }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERCEL: 1

      - name: Build Project Artifacts (Non-Production)
        if: inputs.github-env != 'production'
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
          NEXT_PUBLIC_SENTRY_DISABLED: true

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v42.3.0
        id: deploy-vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-project-name: ${{vars.VERCEL_PROJECT_NAME}}
          prebuilt: true
          github-deployment: true
          github-deployment-environment: ${{ inputs.github-env }}
          target: ${{ inputs.github-env == 'production' && 'production' || 'preview' }}
          vercel-output-dir: .vercel/output

      - name: Notify on Slack
        uses: slackapi/slack-github-action@v3.0.3
        continue-on-error: true
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚀 Deployment to Vercel environment *${{ inputs.github-env }}* was successful. <${{ steps.deploy-vercel.outputs.preview-url }}|View Deployment>"
                  }
                }
              ]
            }
      - name: Abort if Cancelled
        if: cancelled() && steps.deploy-vercel.conclusion == 'started'
        run: |
          curl -X PATCH "https://api.vercel.com/v12/deployments/${{ steps.deploy-vercel.outputs.deployment-id }}/cancel" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json"
